# Generated by Django 2.0.5 on 2018-05-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'keywords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=40)),
                ('keyword', models.CharField(max_length=40)),
                ('user_screen_name', models.CharField(max_length=40)),
                ('user_main_page', models.CharField(max_length=40)),
                ('user_desc1', models.TextField()),
                ('user_desc2_fans', models.CharField(max_length=40)),
                ('user_image_url', models.TextField()),
            ],
            options={
                'db_table': 'userdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Weibodata',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=40)),
                ('weibo_screen_name', models.CharField(max_length=40)),
                ('weibo_scheme', models.TextField()),
                ('weibo_created_at', models.DateField()),
                ('keyword', models.CharField(max_length=40)),
                ('weibo_text', models.TextField()),
                ('weibo_raw_text', models.TextField()),
                ('weibo_comments_count', models.CharField(max_length=40)),
                ('weibo_attitudes_count', models.CharField(max_length=40)),
                ('weibo_reposts_count', models.CharField(max_length=40)),
                ('weibo_pics1', models.TextField(blank=True, null=True)),
                ('weibo_pics2', models.TextField(blank=True, null=True)),
                ('weibo_pics3', models.TextField(blank=True, null=True)),
                ('weibo_pics4', models.TextField(blank=True, null=True)),
                ('weibo_pics5', models.TextField(blank=True, null=True)),
                ('weibo_pics6', models.TextField(blank=True, null=True)),
                ('weibo_pics7', models.TextField(blank=True, null=True)),
                ('weibo_pics8', models.TextField(blank=True, null=True)),
                ('weibo_pics9', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'weibodata',
                'ordering': ['-weibo_created_at'],
                'managed': False,
            },
        ),
    ]
